apiVersion: github.com/microsoft/PSRule/v1
kind: Baseline
metadata:
  name: Baseline.Default
spec:
  rule:
    tag:
      release: GA
  configuration:
    ghasEnabled: true
    ghasBlockPushesEnabled: true
    branchMinimumApproverCount: 1
    releaseMinimumProductionApproverCount: 1
    lastCommitDays: 90
