apiVersion: github.com/microsoft/PSRule/v1
kind: Baseline
metadata:
  name: Baseline.NoExtraLicense
spec:
  rule:
    tag:
      release: GA
    exclude:
      - Azure.DevOps.Repos.GitHubAdvancedSecurityEnabled
      - Azure.DevOps.Repos.GitHubAdvancedSecurityBlockPushes
  configuration:
    branchMinimumApproverCount: 1
    releaseMinimumProductionApproverCount: 1
